# Numpy - Numerical Python Library

In [1]:
#import Numpy Library

import numpy as np

In [2]:
#create simple array from the list

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
#dimension of the array 

print(arr.ndim)

2


In [4]:
#shape of the array

print(arr.shape)

(2, 4)


In [5]:
#type of the array

print(type(arr))

<class 'numpy.ndarray'>


In [6]:
#data memory location  of the array

print(arr.data)

In [7]:
# In 2-D array 
#axis = 0 (column) 
#axis = 1 (Row)


In [8]:
b = np.array([[20,21,22],[25,26,27],[30,31,32]])
print(b , "\n")

[[20 21 22]
 [25 26 27]
 [30 31 32]] 



In [9]:
b.dtype

dtype('int32')

In [10]:
b.itemsize

4

In [11]:
b.size

9

In [12]:
b.shape

(3, 3)

In [13]:
b = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.float64)
print(b, "\n")
print(b.dtype,"\n")
print(b.itemsize)

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

float64 

8


In [14]:
z = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.complex64)
t = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.complex128)
print(z, "\n")
print(z.dtype, "\n")
print(z.itemsize, "\n")
print(t, "\n")
print(t.dtype, "\n")
print(t.itemsize)

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex64 

8 

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex128 

16


In [15]:
#sum value of an array

print(np.sum(b))

234.0


In [16]:
#sum value along a specified axis
print(b, "\n")
print(np.sum(b, axis = 0))
print(np.sum(b,axis = 1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

[75. 78. 81.]
[63. 78. 93.]


In [17]:
#minimize value
print(b, "\n")
print(np.min(b))
print(np.min(b,axis=0))
print(np.min(b,axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

20.0
[20. 21. 22.]
[20. 25. 30.]


In [18]:
#Maximum Value
print(np.max(b))
print(np.max(b,axis=0))
print(np.max(b,axis=1))
print(type(b))

32.0
[30. 31. 32.]
[22. 27. 32.]
<class 'numpy.ndarray'>


In [19]:
#Mean 
print(b, "\n")
print(np.mean(b))
print(np.mean(b,axis=0))
print(np.mean(b,axis=1))
print(type(b))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

26.0
[25. 26. 27.]
[21. 26. 31.]
<class 'numpy.ndarray'>


In [20]:
#standatrd Deviation
print(b, "\n")
print(np.std(b))
print(np.std(b,axis=0))
print(np.std(b,axis=1))
print(type(b))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

4.163331998932265
[4.0824829 4.0824829 4.0824829]
[0.81649658 0.81649658 0.81649658]
<class 'numpy.ndarray'>


In [21]:
# Variance
print(b, "\n")
print(np.var(b))
print(np.var(b,axis=0))
print(np.var(b,axis=1))
print(type(b))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

17.333333333333332
[16.66666667 16.66666667 16.66666667]
[0.66666667 0.66666667 0.66666667]
<class 'numpy.ndarray'>


In [22]:
# Weighted average
print(np.average(b))

26.0


In [23]:
c = np.array([2,4,6, 1,3,5, 8,10,12, 7,9,11])
print(c)

[ 2  4  6  1  3  5  8 10 12  7  9 11]


In [24]:
weight = np.array([0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,])
print(weight)

[0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5 ]


In [25]:
print(np.average(c, weights=weight))

6.444444444444445


In [26]:
#Percentile
print(c, "\n")
print(np.percentile(c,5,0))
print(np.percentile(c,8,0))
print(np.percentile(b,5,1))
print(np.percentile(b,5,0))
print(np.percentile(b,4,0))
print(np.percentile(b,4,1))

[ 2  4  6  1  3  5  8 10 12  7  9 11] 

1.55
1.88
[20.1 25.1 30.1]
[20.5 21.5 22.5]
[20.4 21.4 22.4]
[20.08 25.08 30.08]


In [27]:
#peak to peak 
print(b, "\n")

print(c, "\n")
# difference of maximum and minimum 
print(np.ptp(c,0))
print(np.ptp(b,0))
print(np.ptp(b,1))


[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

[ 2  4  6  1  3  5  8 10 12  7  9 11] 

11
[10. 10. 10.]
[2. 2. 2.]


In [28]:
print(b, "\n")
print(b.shape, "\n")
print(b.reshape(1,9), "\n")
print(b)


[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

(3, 3) 

[[20. 21. 22. 25. 26. 27. 30. 31. 32.]] 

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]]


In [29]:
d = np.array([[20,19,22,5],[25,26,27,18],[30,12,31,32]])
print(d, "\n")
print(np.ptp(d,0))
print(np.ptp(d,1))


[[20 19 22  5]
 [25 26 27 18]
 [30 12 31 32]] 

[10 14  9 27]
[17  9 20]


In [30]:
print(d, "\n")
print(d.shape, "\n")
print(d.reshape(6,2), "\n")
print(d)


[[20 19 22  5]
 [25 26 27 18]
 [30 12 31 32]] 

(3, 4) 

[[20 19]
 [22  5]
 [25 26]
 [27 18]
 [30 12]
 [31 32]] 

[[20 19 22  5]
 [25 26 27 18]
 [30 12 31 32]]


In [31]:
#Slicing
e = [25,35,50,55,70,85,95]
print(e[0:4], "\n")
print(e[-1])

[25, 35, 50, 55] 

95


In [32]:
# 2-D Array
l = np.array([[23,25,27,29],[43,45,47,49],[62,66,68,70]])
print(l, "\n")
print(l[0,3], "\n")
print(l[1,2], "\n")
print(l[2,3], "\n")
print(l[0,1], "\n")
print(l[0:2,1], "\n")
print(l[-1], "\n")
print(l[-1,0:2], "\n")

[[23 25 27 29]
 [43 45 47 49]
 [62 66 68 70]] 

29 

47 

70 

25 

[25 45] 

[62 66 68 70] 

[62 66] 



# STACKING

In [33]:
d = np.arange(12).reshape(3,4)
print(d, "\n")
f = np.arange(12,24).reshape(3,4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [34]:
print(d, "\n")
print(f, "\n")
print(np.hstack((d,f)), "\n")
print(np.hstack((f,d)), "\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]] 

[[12 13 14 15  0  1  2  3]
 [16 17 18 19  4  5  6  7]
 [20 21 22 23  8  9 10 11]] 



In [35]:
print(d, "\n")
print(f, "\n")
print(np.vstack((d,f)), "\n")
print(np.vstack((f,d)), "\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



In [36]:
x = np.array([2,8,10,35,55,60])
y = np.array([1,7,9,34,54,59])
print(x, "\n","\n")
print(y,"\n")
print(x+y, "\n")
print(x-y, "\n")
print(x*y, "\n")
print(x/y, "\n")
print(x//y, "\n")

[ 2  8 10 35 55 60] 
 

[ 1  7  9 34 54 59] 

[  3  15  19  69 109 119] 

[1 1 1 1 1 1] 

[   2   56   90 1190 2970 3540] 

[2.         1.14285714 1.11111111 1.02941176 1.01851852 1.01694915] 

[2 1 1 1 1 1] 



In [37]:
import numpy as np
print(np.zeros((4,3)), "\n")
print(np.ones((4,3)), "\n")
#IT IS ONLY POSSIBLE FOR ONES AND ZEROS ONLY

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



In [38]:
from numpy import random
x = random.randint(100)
print(x)

3


In [39]:
#GENRATE RANDOM FLOAT
x = random.rand(3)
print(x)

[0.29206536 0.19056428 0.71038526]


In [40]:
#GENRATE RANDOM ARRAY

from numpy import random
x = random.randint(100, size = (8))
print(x)

[91  2 48  4 42  7 69 14]


In [41]:
#GENRATE RANDOM FLOAT WITH MULTIPLE NUMBER
x = random.rand(6)
print(x)

[0.80091529 0.18852162 0.13171495 0.7976287  0.15600404 0.81697187]


In [42]:
#GENRATE A 2-D ARRAY WITH 3 ROWS, EACH ROW CONTAINING 5 RANDOM INTEGER FROM 0 TO 100

from numpy import random
x = random.randint(100, size = (3,5))
print(x)

[[79 84 43 88 41]
 [ 3 97 71 40 79]
 [90  8 85 91 17]]


In [43]:
#Creating scalars in Numpy
#numpy.asscalar()

import numpy as np
in_arr = np.array([8])

print("input array is ", in_arr)

out_scalar = np.ndarray(in_arr)
print("output scalar from input array ", out_scalar)

input array is  [8]
output scalar from input array  [4.67296746e-307 1.69121096e-306 1.78019082e-306 1.89146896e-307
 7.56571288e-307 3.11525958e-307 1.24610723e-306 1.29061142e-306]


# Creating Vector in Numpy

In [44]:
#CREATING THE VECTOR IN NUMPY

#IMPORT NUMPY

import numpy as np

#CRATING 1-D LIST
list1 = [1, 2, 3]

#CRATING 1-D LIST vertical
list2 = [[10],
          [20],
          [30]]
    
#CRATING VECTOR1
vector1 = np.array(list1)
vector2 = np.array(list2)

print("HORIZONTAL Vector")
print(vector1)

print("-------------------")

print("VERTICAL Vector")
print(vector2)


HORIZONTAL Vector
[1 2 3]
-------------------
VERTICAL Vector
[[10]
 [20]
 [30]]


# Creating matrix in Numpy

In [45]:
import numpy as np

a = np.matrix('1 2; 3 4')
print("via string input : \n", a, "\n\n")

#ARRAY-LIKE INPUT
b = np.matrix([[5, 6, 7], [4, 6]])
print("via array-like input : \n", b)


via string input : 
 [[1 2]
 [3 4]] 


via array-like input : 
 [[list([5, 6, 7]) list([4, 6])]]


C:\Users\patel\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


# Matrix Multiplication in Numpy

In [46]:
import numpy as np

A = 5 

B = [[6, 7],
    [8, 9]]

print(np.dot(A,B))

[[30 35]
 [40 45]]


In [47]:
import numpy as np

A = [[6, 7],
    [8, 9]]

B = [[1, 3],
    [5, 7]]

print(np.dot(A,B))

print("-------------")

print(np.dot(B,A))

[[41 67]
 [53 87]]
-------------
[[30 34]
 [86 98]]


# Percentile and Interquartile in Numpy

In [48]:
#PERCENTILE & INTERQURTILE IN NUMPY

import numpy as np
data = [32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92, 93, 96, 97, 101, 105, 112, 116]

#FIRST QUARTILE(Q1)

Q1 = np.median(data[:10])

#THIERD quartile
Q3 = np.median(data[10:])

#interquartile range

IQR = Q3-Q1

print(IQR)
print(Q3)

34.0
96.5


# Array Broadcasting in Numpy

In [49]:
#ARRAY BRODCASTING IN NUMPY

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

a * b


array([2., 4., 6.])

In [50]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0

a * b

array([2., 4., 6.])